{
 "title": "Proiect PR",
 "time": { "from": "2025-01-10T18:01:58.544Z", "to": "2025-01-10T18:06:58.544Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -6h) \r\n  |> filter(fn: (r) => r[\"key\"] == \"nivel_apa\")\r\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\") \r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r[\"key\"] == \"stare_pompa\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"key\"]) \r\n  |> last()  // Get the last (most recent) value"
    }
   ]
  },
  {
   "title": "Pump state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r[\"key\"] == \"stare_pompa\")\r\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\r\n\r\n  "
    }
   ]
  },
  {
   "title": "SOIL MOISTURE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r[\"key\"] == \"umiditate_sol\")\r\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false) \r\n  |> yield(name: \"mean\") \r\n"
    }
   ]
  },
  {
   "title": "CURRENT SOIL MOISTURE LEVEL",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r[\"key\"] == \"umiditate_sol\")\r\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false) \r\n  |> yield(name: \"mean\")\r\n  "
    }
   ]
  },
  {
   "title": "CURRENT WATER LEVEL",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r[\"key\"] == \"nivel_apa\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "WATER LEVEL HISTORY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: -6h) \r\n  |> filter(fn: (r) => r[\"key\"] == \"nivel_apa\")\r\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\") \r\n"
    }
   ]
  }
 ]
}